# Generated by Django 4.1 on 2022-08-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0003_rename_alphatables_alphatable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alphatable',
            new_name='Alphatables',
        ),
    ]
