# Generated by Django 4.1 on 2022-08-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0006_rename_email_site_visitor_email_addy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_visitor',
            old_name='name',
            new_name='names',
        ),
    ]
