# Generated by Django 4.1 on 2022-08-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0007_rename_name_site_visitor_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_visitor',
            old_name='names',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='site_visitor',
            name='email_addy',
        ),
        migrations.AddField(
            model_name='site_visitor',
            name='email',
            field=models.EmailField(default='this is it', max_length=30),
        ),
    ]
