# Generated by Django 4.1 on 2022-08-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0008_rename_names_site_visitor_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='site_visitor',
            new_name='Alphanumeric',
        ),
    ]
