# Generated by Django 4.1 on 2022-08-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0009_rename_site_visitor_alphanumeric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alphanumeric',
            new_name='Alphanum',
        ),
    ]
