# Generated by Django 4.1 on 2022-08-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0011_rename_alphanum_alphanumeric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alphanumeric',
            new_name='site_visitor',
        ),
    ]
