# Generated by Django 4.1 on 2022-08-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0014_alter_alphaguide_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphaguide',
            name='Attribute',
            field=models.TextField(max_length=1500),
        ),
    ]
