# Generated by Django 4.1 on 2022-08-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0017_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='NameField',
        ),
    ]
