# Generated by Django 4.1 on 2022-08-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0018_rename_name_namefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='namefield',
            name='thisresult',
            field=models.TextField(blank=True, null=True),
        ),
    ]
