# Generated by Django 4.1 on 2022-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0019_namefield_thisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namefield',
            name='thisresult',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
