# Generated by Django 4.1 on 2022-08-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingg', '0020_alter_namefield_thisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='namefield',
            name='thisresult1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult5',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult6',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult7',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult8',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='namefield',
            name='thisresult9',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
